# 01. Data Exploration

## Setup

In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')

from config import config

In [2]:
from src.data_inspection import print_column_values

In [3]:
import pandas as pd 

df=pd.read_csv("C:\\Users\\Rathishan\\Desktop\\Desktop\\Git\\ML_Module\\Machine-Learning-Based-Fetal-Well-being-Classification-Using-Cardiotocography-Features\\data\\raw\\metadata.csv")

C:\Users\Rathishan\AppData\Local\Temp\ipykernel_7496\1475954230.py:3: DtypeWarning: Columns (2,3,5,6,7,8,10,12,19,20,30,33,34,35,36,37,38,42,43,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("C:\\Users\\Rathishan\\Desktop\\Desktop\\Git\\ML_Module\\Machine-Learning-Based-Fetal-Well-being-Classification-Using-Cardiotocography-Features\\data\\raw\\metadata.csv")

In [4]:
df.head()

,record_id,patient_id,gravidity,parity,gestational_age,total_labor_hr,total_labor_min,first_stage_hr,first_stage_min,second_stage_hr,...,FU_V_XWTTF,FU_S_XWTTF,FU_K_XWTTF,FU_C_XWTTF,NetFea_0,NetFea_1,NetFea_2,NetFea_3,NetFea_4,figo_label
0,10000_1_210208000001,1,2,1.0,38,6.0,27,6,0,NaN,...,48824.95847,0.906524,3.098757,0.803414,1.303176,1.932325,0.472173,2.461688,2.572995,1
1,10003_1_210208000001,2,3,1.0,39+5,2.0,15,2,0,0,...,58806.40840,0.754356,2.519955,0.870584,-0.599488,-2.680991,-0.874607,-0.983837,-0.066794,1
2,10004_1_210208000001,3,1,0.0,38+4,10.0,15,9,0,1,...,44534.54236,0.763957,2.739259,0.783653,-1.940863,-3.777680,-0.282407,-0.368363,0.649024,0
3,10005_1_210208000001,4,3,2.0,39+2,3.0,55,3,30,NaN,...,35008.16836,0.750787,2.796813,0.746308,-2.995938,-3.151090,-0.472669,-1.271450,-1.228886,0
4,10006_1_210208000001,5,2,1.0,40,4.0,55,4,40,0,...,40149.20607,0.518829,2.339740,0.718667,-1.892708,-3.511985,-0.099267,-1.753792,0.476429,0

In [5]:
df.shape

(20769, 215)

In [6]:
columns =df.columns.tolist()

In [7]:
print_column_values(df, columns, 1, 10)

Showing columns 1 to 10

,record_id,patient_id,gravidity,parity,gestational_age,total_labor_hr,total_labor_min,first_stage_hr,first_stage_min,second_stage_hr
0,10000_1_210208000001,1,2,1.0,38,6.0,27,6,0,NaN
1,10003_1_210208000001,2,3,1.0,39+5,2.0,15,2,0,0
2,10004_1_210208000001,3,1,0.0,38+4,10.0,15,9,0,1
3,10005_1_210208000001,4,3,2.0,39+2,3.0,55,3,30,NaN
4,10006_1_210208000001,5,2,1.0,40,4.0,55,4,40,0
5,10007_1_210208000001,6,3,0.0,40,3.0,13,2,50,0
6,10010_1_210208000001,7,3,0.0,39+3,11.0,5,10,30,0
7,10011_1_210208000001,8,1,0.0,38+2,4.0,40,3,0,1
8,10013_1_210208000001,9,1,0.0,39+4,10.0,18,9,10,1
9,10014_1_210208000001,9,1,0.0,39+4,10.0,18,9,10,1

In [15]:
print_column_values(df, columns, 11, 20)

Showing columns 11 to 20

,second_stage_min,third_stage_hr,third_stage_min,delivery_spontaneous_vaginal,delivery_vacuum,delivery_forceps,delivery_cesarean,delivery_breech_assisted,delivery_breech_extraction,birth_weight_kg
0,22,NaN,5.0,True,False,False,False,False,False,3.15
1,10,0,5.0,True,False,False,False,False,False,3.3
2,10,0,5.0,True,False,False,False,False,False,3.7
3,25,NaN,5.0,True,False,False,False,False,False,3.4
4,7,0,8.0,True,False,False,False,False,False,3.25
5,18,0,5.0,True,False,False,False,False,False,2.9
6,30,0,5.0,True,False,False,False,False,False,2.95
7,35,0,5.0,True,False,False,False,False,False,3.0
8,3,0,5.0,True,False,False,False,False,False,3.6
9,3,0,5.0,True,False,False,False,False,False,3.6

In [16]:
print_column_values(df, columns, 21, 30)

Showing columns 21 to 30

,birth_head_circumference_cm,birth_length_cm,postpartum_bleeding_2hr_ml,placenta_fetal_side,placenta_maternal_side,placenta_spontaneous,placenta_manual_removal,placenta_intact,placenta_mostly_intact,placenta_incomplete
0,33.0,50.0,200,True,False,True,False,True,False,False
1,35.0,49.0,160,True,False,True,False,False,False,False
2,35.0,51.0,200,True,False,True,False,False,True,False
3,33.0,50.0,250,True,False,True,False,True,False,False
4,33.0,50.0,220,True,False,True,False,True,False,False
5,32.0,46.0,200,True,False,True,False,True,False,False
6,34.0,49.0,180,True,False,True,False,False,True,False
7,34.0,50.0,180,True,False,True,False,False,True,False
8,33.0,50.0,850,True,False,True,False,False,False,True
9,33.0,50.0,850,True,False,True,False,False,False,True